import { Roboto } from 'next/font/google'
import './globals.css'
import NextAuthSessionProvider from '@/providers/NextAuthSessionProvider'
import { Toaster } from '@/components/ui/toaster'

const roboto = Roboto({
	weight: ['300', '400', '500', '700'],
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-roboto'
})

export const metadata = {
	title: 'HR App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${roboto.variable} font-sans antialiased`}>
				<NextAuthSessionProvider>{children}</NextAuthSessionProvider>
				<Toaster />
			</body>
		</html>
	)
}
